name: tests

on: [push, pull_request]

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.8
            toxenv: flake8
            os: ubuntu-latest
          - python: 3.8
            toxenv: mypy
            os: ubuntu-latest
          - python: 3.8
            toxenv: pylint
            os: ubuntu-latest
          - python: 3.8
            toxenv: black
            os: ubuntu-latest
          - python: 3.7
            toxenv: py37
            os: ubuntu-latest
          - python: 3.8
            toxenv: py38
            os: ubuntu-latest
          - python: 3.8
            toxenv: py38
            os: macos-latest
          - python: 3.8
            toxenv: py38
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{  matrix.python }}
      - name: install dependencies
        run: python -m pip install --upgrade pip tox
      - name: run
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox

  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install -r requirements-dev.txt
          python setup.py egg_info
          python -m pip install -r iceart.egg-info/requires.txt
          py.test --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
